env_id: antmaze-medium-v0
feat:
  type: state
  dim: 256
training:
  num_steps: 1000000
  batch_size: 256
  eval_every: 10000
  save_every: 50000
model:
  lr: 1e-4
  embed_dim: 256
  embed_type: positional
  beta_min: 0.1
  beta_max: 20.0
  num_steps: 1000
  continuous: True
  input_dim: 129  # Add this field for AntMaze
sampling:
  predictor: ddim
  corrector: none
  n_inference_steps: 100
  eta: 0.0
planning:
  planner: random_shooting
  num_samples: 1000
  num_elites: 100
  guidance_coef: 1.0